spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Cats
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
server:
  port: 8082

